controller_list:
  - name: fake_full_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses per group
  - group: full_arm_group
    pose: zero_pose