# -*- coding: utf-8 -*-
"""devel_RUN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M9HQWOOYMh1TokYruPvXT0OYveqSRl_a
"""

import numpy as np
import pandas as pd
import math
# Пример данных
df = pd.read_csv('wing_sheet_fixed.csv')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

output_file_path = 'inv_waypoints.txt'

# Открываем файл для записи
with open(output_file_path, 'w') as file:
    # Ваш массив градусов
# Ваш массив градусов
    degrees_array = np.array([5 + 30/60,5,4 + 21/60,3 + 34/60,1 + 51/60,0 - 12/30,-2 - 43/60,-5 - 1/60,-5 - 38/60,-8 - 52/60])
    # Перевод в радианы
    degrees_array = np.flip(degrees_array)
    radians_array = np.radians(degrees_array)
    matrix = np.vstack([degrees_array, np.zeros((25, len(degrees_array)))])
    df_deg = pd.DataFrame(matrix)
    for i in range(0, 10, 1):
      k = np.linspace(0, df_deg.iloc[0,i], 26)
      df_deg[i] = k
    multiply = np.linspace(3.5, 3, 5)
    #multiply = np.array(multiply)
    for i in range(0,5):
      multiply = np.append(multiply, 1)
    multiply = np.flip(multiply)
    new_df = df_deg
    # Создание новой строки с пустыми значениями
    new_row = pd.DataFrame([multiply], columns=new_df.columns)
    # Вставка новой строки в начало DataFrame
    new_df = pd.concat([new_row, new_df]).reset_index(drop=True)
    # Вставка новой строки в начало DataFrame
    new_df = pd.concat([new_row, new_df]).reset_index(drop=True)
    for i in range(0,22,2):
      new_column_name = None
      new_df.insert(loc=i, column=new_column_name, value=None)
    new_df[None] = None
    
    # Записываем первую строку в файл
    #file.write(f'"r{df.columns[1]}"= "{df.loc[0,"A1 - A1"]}"\n' )
    revers = True
    for i in range(df.shape[1]-2, 1, -2):
      print(new_df.iloc[1,i-1])
      revers = not revers
      # значение переменной Xpos (сколько ехать вперёд)
      Ypos = float(df.iloc[0,i-1])
      Ypos = 245 - Ypos
      if revers == False:
        # Записываем остальные строки в файл
        for j in range(2, df.shape[0], 1):
            #Записываем Xpos
            file.write(f'{df.iloc[j,0]},')
            # Значение переменной Ypos
            file.write(f'{Ypos},')
            # Значение переменной Zpos
            file.write(f'{df.iloc[j,i-1]},')
            file.write(f'{new_df.iloc[j,i-1]},')
            file.write(f'{new_df.iloc[0,i-1]}\n')
            # Значение переменной _yc
            #file.write(f'"{col2_name}_yc_{index - 2}"= {row[i+1]}\n')
      else:
          for j in range(df.shape[0]-1, 1, -1):
              #Записываем Xpos
            file.write(f'{df.iloc[j,0]},')
            # Значение переменной Ypos
            file.write(f'{Ypos},')
            # Значение переменной Zpos
            file.write(f'{df.iloc[j,i-1]},')
            file.write(f'{new_df.iloc[j,i-1]},')
            file.write(f'{new_df.iloc[0,i-1]}\n')

"""## ДЛЯ верхней части"""

output_file_path = 'inv_waypoints_yc.txt'

# Открываем файл для записи
with open(output_file_path, 'w') as file:

    # Записываем первую строку в файл
    #file.write(f'"r{df.columns[1]}"= "{df.loc[0,"A1 - A1"]}"\n' )
    revers = False
    for i in range(df.shape[1]-2, 1, -2):
      revers = not revers
      # значение переменной Xpos (сколько ехать вперёд)
      Ypos = float(df.iloc[0,i-1])
      Ypos = 245 - Ypos
      if revers == False:
        # Записываем остальные строки в файл
        for j in range(2, df.shape[0], 1):
            #Записываем Xpos
            file.write(f'{df.iloc[j,0]},')
            # Значение переменной Ypos
            file.write(f'{Ypos},')
            # Значение переменной Zpos
            file.write(f'{df.iloc[j,i]},')
            file.write(f'{k[j-2]}\n')

            # Значение переменной _yc
            #file.write(f'"{col2_name}_yc_{index - 2}"= {row[i+1]}\n')
      else:
          for j in range(df.shape[0]-1, 1, -1):
              #Записываем Xpos
            file.write(f'{df.iloc[j,0]},')
            # Значение переменной Ypos
            file.write(f'{Ypos},')
            # Значение переменной Zpos
            file.write(f'{df.iloc[j,i]},')
            file.write(f'{k[j-1]}\n')

wpk = pd.read_csv('inv_waypoints.txt', header=None)
wpc = pd.read_csv('inv_waypoints_yc.txt', header=None)
wpk = wpk.dropna()
wpc = wpc.dropna()
wpk.to_csv('inv_waypoints.txt', index=False, header=False)
wpc.to_csv('inv_waypoints_yc.txt', index=False, header=False)