# -*- coding: utf-8 -*-
"""devel_RUN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M9HQWOOYMh1TokYruPvXT0OYveqSRl_a
"""

import numpy as np
import pandas as pd


# Пример данных
df = pd.read_csv('wing_sheet_fixed.csv')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

output_file_path = 'waypoints.txt'

# Открываем файл для записи
with open(output_file_path, 'w') as file:

    # Записываем первую строку в файл
    #file.write(f'"r{df.columns[1]}"= "{df.loc[0,"A1 - A1"]}"\n' )
    revers = True
    for i in range(1, df.shape[1]-1, 2):
      revers = not revers
      # значение переменной Xpos (сколько ехать вперёд)
      Ypos = float(df.iloc[0,i])
      Ypos = 310 - Ypos
      if revers == False:
        # Записываем остальные строки в файл
        for j in range(2, df.shape[0], 1):
            #Записываем Xpos
            file.write(f'{df.iloc[j,0]},')           
            # Значение переменной Ypos
            file.write(f'{Ypos},')
            # Значение переменной Zpos
            file.write(f'{df.iloc[j,i]}\n')

            # Значение переменной _yc
            #file.write(f'"{col2_name}_yc_{index - 2}"= {row[i+1]}\n')
      else:
          for j in range(df.shape[0]-1, 1, -1):
              #Записываем Xpos
            file.write(f'{df.iloc[j,0]},')           
            # Значение переменной Ypos
            file.write(f'{Ypos},')
            # Значение переменной Zpos
            file.write(f'{df.iloc[j,i]}\n')

"""## ДЛЯ верхней части"""

output_file_path = 'waypoints_yc.txt'

# Открываем файл для записи
with open(output_file_path, 'w') as file:

    # Записываем первую строку в файл
    #file.write(f'"r{df.columns[1]}"= "{df.loc[0,"A1 - A1[ERROR] [1708268792.114262002, 184.500000000]: Unable to sample a point inside the constraint region
      # значение переменной Xpos (сколько ехать вперёд)
      Ypos = float(df.iloc[0,i])
      Ypos = 310 - Ypos
      if revers == False:
        # Записываем остальные строки в файл
        for j in range(2, df.shape[0], 1):
            #Записываем Xpos
            file.write(f'{df.iloc[j,0]},')            
            # Значение переменной Ypos
            file.write(f'{Ypos},')
            # Значение переменной Zpos
            file.write(f'{df.iloc[j,i+1]}\n')

            # Значение переменной _yc
            #file.write(f'"{col2_name}_yc_{index - 2}"= {row[i+1]}\n')
      else:
          for j in range(df.shape[0]-1, 1, -1):
              #Записываем Xpos
            file.write(f'{df.iloc[j,0]},')            
            # Значение переменной Ypos
            file.write(f'{Ypos},')
            # Значение переменной Zpos
            file.write(f'{df.iloc[j,i+1]}\n')

# чистка данных от NaN
wpk = pd.read_csv('waypoints.txt', header=None)
wpc = pd.read_csv('waypoints_yc.txt', header=None)
wpk = wpk.dropna()
wpc = wpc.dropna()
wpk.to_csv('waypoints.txt', index=False, header=False)
wpc.to_csv('waypoints_yc.txt', index=False, header=False)